#! /bin/bash
apt-get update
apt install apache2 -y
apt install -y mysql-client mysql-server

chmod +x script_change_pass
#change pass and import sql
./script_change_pass $1
#install code and config apache.conf
./script_install_code
# ifconfig
apt install -y net-tools -y
# php
apt install -y php7.4
apt install -y php7.4-common php7.4-mysql php7.4-xml php7.4-xmlrpc php7.4-curl php7.4-gd php7.4-imagick php7.4-cli php7.4-dev php7.4-imap php7.4-mbstring php7.4-opcache php7.4-soap php7.4-zip php7.4-intl -y
apt install -y phpmyadmin php-mbstring php-zip php-gd php-json php-curl
ln -s /usr/share/phpmyadmin /var/www/html/
# zip
apt install zip -y
./script_set_up_crontab $1
# install snapd
apt install snapd
# install vscode
sudo apt install snapd