#! /bin/bash
PASSWORD=$1
#change passs
mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${PASSWORD}';"
#create and insert
mysql -u root -p${PASSWORD} -e "CREATE DATABASE giuaky2"
mysql -u root -p${PASSWORD} giuaky2 < giuaky2.sql
# mysql -e "CREATE USER '${MAINDB}'@'localhost' IDENTIFIED WITH 'caching_sha2_password' BY '${PASSWDDB}';"
# mysql -e "GRANT ALL PRIVILEGES ON ${MAINDB}.* TO 'phpmyadmin'@'localhost' WITH GRANT OPTION;"